version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jam_factory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5440:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
