openapi: 3.0.3
info:
  title: JamFactory API
  version: 1.0.0
  description: API for creating jam production plans at JamFactory

servers:
  - url: http://localhost:8080/api/v1
    description: Jam server

tags:
  - name: ProductionPlans
    description: Endpoints related to creating jam production plans.

paths:
  /jams/product-plan:
    post:
      tags:
        - ProductionPlans
      summary: Create a new jam production plan
      operationId: createJamProductionPlan
      requestBody:
        description: Details of the production plan
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JamProductionPlanRequest'
      responses:
        '201':
          description: Production plan created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionPlanResponse'
        '422':
          description: Business logic error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessErrorResponse'
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplementedError'

    get:
      tags:
        - ProductionPlans
      summary: Get the production plan overview for the next 7 days
      operationId: getProductionPlan
      responses:
        '200':
          description: Production plan retrieved successfully for the next 7 days
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionPlanOverviewResponse'
        '400':
          description: Error retrieving the production plan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductionPlanErrorResponse'

  /jars/order/update/{id}:
    put:
      tags:
        - ProductionPlans
      summary: Update the production plan based on the provided UUID
      operationId: updateProductionPlan
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the production plan to update
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      responses:
        '204':
          description: Order updated successfully, no content returned
        '501':
          description: Not Implemented
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotImplementedError'

components:
  schemas:
    JamProductionPlanRequest:
      type: object
      properties:
        planDate:
          type: string
          format: date
          example: "2024-09-01"
        smallJamJars:
          type: integer
          example: 100
        mediumJamJars:
          type: integer
          example: 50
        largeJamJars:
          type: integer
          example: 20
      required:
        - planDate
        - smallJamJars
        - mediumJamJars
        - largeJamJars

    ProductionPlanResponse:
      type: object
      properties:
        planId:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"

    BusinessErrorResponse:
      type: object
      properties:
        rejectReason:
          type: string
          example: "przekraczająca zdolność produkcyjna"

    ProductionPlanErrorResponse:
      type: object
      properties:
        reason:
          type: string
          example: "Błąd dodania planu produkcyjnego - przekroczono XXXXXX"
        code:
          type: string
          example: "JAM_DAILY_PRODUCTION_LIMIT_EXCEDED"

    NotImplementedError:
      type: object
      properties:
        error:
          type: string
          example: "Not Implemented"

    ProductionPlanOverviewResponse:
      type: object
      properties:
        perDay:
          type: array
          items:
            type: object
            properties:
              date:
                type: string
                format: date
                example: "2024-08-12"
              M:
                type: integer
                example: 500
              L:
                type: integer
                example: 300
              S:
                type: integer
                example: 200
        sum:
          type: object
          properties:
            M:
              type: integer
              example: 1100
            L:
              type: integer
              example: 900
            S:
              type: integer
              example: 600
